In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("State Info_1.csv")

In [3]:
df.head()

,id,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,Electoral Votes,9,3,11,6,55,9,7,3,3,...,3,11,38,6,3,13,12,5,10,3
1,Registered Voters,2490000,337000,3262000,1262000,15690000,2645000,1726000,472000,500675,...,429000,3183000,11634000,1443000,343000,4159000,3852000,892000,3129000,268000
2,Population,4908620,734002,7378490,3039000,39937500,5845530,3563080,982895,705749,...,903027,6897580,29472300,3282120,628061,8626210,7797100,1778070,5851750,567025
3,Percentage of Population,50.73%,45.91%,44.21%,41.53%,39.29%,45.25%,48.44%,48.02%,70.94%,...,47.51%,46.15%,39.47%,43.97%,54.61%,48.21%,49.40%,50.17%,53.47%,47.26%
4,Party plurality,Republican,Republican,Republican,Republican,Democratic,Democratic,Democratic,Democratic,Democratic,...,Republican,Republican,Republican,Republican,Democratic,Democratic,Democratic,Republican,Republican,Republican

In [4]:
df.set_index("id",inplace=True)

In [5]:
df.head()

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
id,,,,,,,,,,,,,,,,,,,,,
Electoral Votes,9,3,11,6,55,9,7,3,3,29,...,3,11,38,6,3,13,12,5,10,3
Registered Voters,2490000,337000,3262000,1262000,15690000,2645000,1726000,472000,500675,9435000,...,429000,3183000,11634000,1443000,343000,4159000,3852000,892000,3129000,268000
Population,4908620,734002,7378490,3039000,39937500,5845530,3563080,982895,705749,21993000,...,903027,6897580,29472300,3282120,628061,8626210,7797100,1778070,5851750,567025
Percentage of Population,50.73%,45.91%,44.21%,41.53%,39.29%,45.25%,48.44%,48.02%,70.94%,42.90%,...,47.51%,46.15%,39.47%,43.97%,54.61%,48.21%,49.40%,50.17%,53.47%,47.26%
Party plurality,Republican,Republican,Republican,Republican,Democratic,Democratic,Democratic,Democratic,Democratic,Republican,...,Republican,Republican,Republican,Republican,Democratic,Democratic,Democratic,Republican,Republican,Republican

In [6]:
polls_df=pd.read_csv("Polls.csv")

In [7]:
polls_df.head()

,Name,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,Joe Biden,39.0,40.0,47.1,45.0,58.0,56.0,55.9,45.9,96.2,...,40.0,42.0,44.0,41.0,67.9,51.0,59.0,31.0,51.0,30.0
1,Donald Trump,53.0,45.0,45.4,47.0,30.0,39.0,33.0,40.2,3.8,...,60.0,51.0,48.0,44.0,32.1,39.0,37.0,66.0,43.0,69.9
2,Undecided,8.0,15.0,7.5,8.0,12.0,5.0,11.1,13.9,0.0,...,0.0,7.0,8.0,15.0,0.0,10.0,4.0,3.0,6.0,0.1
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
polls_df.set_index("Name", inplace=True)

In [ ]:
polls_json=polls_df.head(3)